### PR TITLE
Allow Trusted Anchor, Private Key and Certificate to be in PMEM

### PR DESCRIPTION
**Pull request by s-hadinger**
Using pre-parsed TA, PrivKey and Chain (generated from bearssl CLI) directly in PMEM requires additional changes.

It was tested with RSA Trusted Anchor, and EC P256R1 Private Key + Certificate.

### CODE REVIEW

**Comment by s-hadinger** [comment]
Oops, I pushed the PR #14 on top of PR #13.
I hope it's ok, otherwise I'll create it separately.

**Comment by earlephilhower** [comment]
Sure, it will clear up after I merge your prior one. I'm a bit busy this week, but should be able to test the other one and merge by this weekend.

**Comment by s-hadinger** [comment]
I ran the BearSSL tests on Linux:

- `./build/testcrypto all` OK
- `./build/testx509` OK
- `mono Twrch.exe conf/bearssl.json` total = 1871, failed = 0

**Comment by earlephilhower** [comment]
Argh, looks like for some reason it is not removing the montymul changes which are already in the main repo.  Not sure exactly what's going on, it may be something to do with the git branch structure you were using.

Would it be possible to copy the changes here into another branch off of the updated master and make a new PR?  I can't edit this to drop the other file...

**Review by earlephilhower — CHANGES_REQUESTED** [review]
Changes seem fine to me, but I can't fix the extra file on my end...

**Comment by s-hadinger** [comment]
Done in #15

**Pull request closed without merging**
